[package]
name = "output_derive"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
output = { path = ".." }
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
