language: rust
rust:
- stable
- beta
- nightly

matrix:
  include:
  - rust: 1.29.1
    env: CLIPPY=YESPLEASE
    before_script: rustup component add clippy-preview
    script: cargo clippy --all-targets --all -- -D warnings
  - rust: 1.29.1
    env: RUSTFMT=YESPLEASE
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check

branches:
  except:
  - staging.tmp

cache: cargo

notifications:
  email:
    on_success: never
